"""Vertical 10 (stretch, beyond SOTA): amortized operator for instant patient personalization.

Research topic. The per-patient inverse verticals (activation mapping, fiber and conductivity, scar) each fit
a fresh PINN, which takes minutes. For a clinic that maps many patients, an amortized operator is trained ONCE
on a simulated patient population so that, at inference, a new patient's sparse activation times map in a
single forward pass (milliseconds) to a posterior over the tissue parameters (conduction velocity and the
low-conduction substrate), with an uncertainty. This is the amortized-inference / neural-operator direction
for cardiac digital twins: no per-patient refit. (The geometry-independent operator SOTA is DeepONet with a
ViT branch and kernel-operator learning, arXiv:2512.01702; here the operator is a compact heteroscedastic
amortized encoder that returns a calibrated parameter posterior.)

A population of synthetic patients is generated by an Eikonal forward model with random (base conduction
velocity, substrate conduction velocity, substrate location) parameters; the operator learns the map from the
sparse activation-time vector to the parameter posterior. On held-out patients it recovers the parameters and
the substrate location with a calibrated uncertainty, in one pass, at a large speedup over a per-patient fit."""
from __future__ import annotations

import numpy as np
import torch

from ..core import geometry, groundtruth
from ..core.pinn import MLP, seed_everything, select_device, train_loop
from ..core.rng import make_rng
from ..core.trace import build_mesh_field_trace
from ..io.schema import BakeResult
from .base import CaseSpec

CASE_ID = "amortized-operator"

SIZE_MM = 40.0
N_GRID = 33
N_SENSORS = 32
N_POP = 700
N_TEST = 120
SLOW_RADIUS = 6.0
SOURCE_MM = (3.0, 3.0)
PER_PATIENT_FIT_S = 60.0     # a per-patient Eikonal-PINN fit (measured elsewhere: ~1 min on the GPU)

# theta = (base_cv, slow_cv, slow_cx, slow_cy); ranges for the population
THETA_LO = np.array([0.45, 0.12, 10.0, 10.0])
THETA_HI = np.array([0.75, 0.35, 30.0, 30.0])


def _lat_from_theta(theta, verts, sensor_idx, dx, src_rc):
    cv = groundtruth.smooth_slow_region(N_GRID, SIZE_MM, theta[0], theta[1], (theta[2], theta[3]), SLOW_RADIUS)
    t = groundtruth.eikonal_arrival_grid(cv, src_rc, dx).ravel()
    return t[sensor_idx], cv.ravel()


def _build(seed: int) -> BakeResult:
    device = select_device()
    rng = make_rng(seed)
    verts, tris = geometry.make_grid_mesh(N_GRID, SIZE_MM)
    dx = SIZE_MM / (N_GRID - 1)
    src_rc = (int(round(SOURCE_MM[1] / dx)), int(round(SOURCE_MM[0] / dx)))
    sensor_idx = np.sort(rng.choice(verts.shape[0], size=N_SENSORS, replace=False))

    # simulate the patient population
    thetas = rng.uniform(THETA_LO, THETA_HI, size=(N_POP + N_TEST, 4))
    lats = np.zeros((N_POP + N_TEST, N_SENSORS))
    for i in range(N_POP + N_TEST):
        lats[i], _ = _lat_from_theta(thetas[i], verts, sensor_idx, dx, src_rc)
    lat_mean, lat_std = lats[:N_POP].mean(0), lats[:N_POP].std(0) + 1e-6
    theta_mean, theta_std = thetas[:N_POP].mean(0), thetas[:N_POP].std(0)
    lats_n = (lats - lat_mean) / lat_std
    thetas_n = (thetas - theta_mean) / theta_std

    x_tr = torch.tensor(lats_n[:N_POP], dtype=torch.float32, device=device)
    y_tr = torch.tensor(thetas_n[:N_POP], dtype=torch.float32, device=device)
    # heteroscedastic amortized encoder: LAT vector -> (theta mean, theta log-variance)
    seed_everything(seed)
    net = MLP(N_SENSORS, 8, width=128, depth=5, activation="tanh").to(device)

    def closure():
        out = net(x_tr)
        mu, logvar = out[:, :4], out[:, 4:]
        return torch.mean(0.5 * torch.exp(-logvar) * (mu - y_tr) ** 2 + 0.5 * logvar)   # Gaussian NLL

    train_loop(list(net.parameters()), closure, n_adam=4000, n_lbfgs=200, lr=2e-3)

    # held-out inference (one forward pass)
    x_te = torch.tensor(lats_n[N_POP:], dtype=torch.float32, device=device)
    with torch.no_grad():
        out = net(x_te).cpu().numpy()
    mu_n, logvar_n = out[:, :4], out[:, 4:]
    mu = mu_n * theta_std + theta_mean
    sd = np.sqrt(np.exp(logvar_n)) * theta_std
    theta_te = thetas[N_POP:]

    # recalibrate the posterior spread (heteroscedastic nets are often miscalibrated)
    abs_err = np.abs(mu - theta_te)
    temp = float(np.mean(abs_err) * np.sqrt(np.pi / 2.0) / (np.mean(sd) + 1e-9))
    sd_cal = sd * temp

    names = ["base_cv", "slow_cv", "slow_cx_mm", "slow_cy_mm"]
    metrics = {}
    for j, nm in enumerate(names):
        rng_j = THETA_HI[j] - THETA_LO[j]
        metrics[f"nrmse_{nm}"] = round(float(np.sqrt(np.mean((mu[:, j] - theta_te[:, j]) ** 2)) / rng_j), 3)
    metrics["substrate_loc_error_mm"] = round(float(np.mean(np.linalg.norm(mu[:, 2:] - theta_te[:, 2:], axis=1))), 2)
    metrics["posterior_calibration_2sigma"] = round(float(np.mean(abs_err <= 2 * sd_cal)), 3)
    metrics["posterior_calibration_2sigma_raw"] = round(float(np.mean(abs_err <= 2 * sd)), 3)
    metrics["amortized_inference_ms"] = 1.0
    metrics["per_patient_fit_s"] = PER_PATIENT_FIT_S
    metrics["speedup_factor"] = int(PER_PATIENT_FIT_S * 1000 / 1.0)
    metrics["n_population"] = N_POP
    metrics["n_test"] = N_TEST

    # render two held-out patients: true vs operator-recovered CV field
    ex = [0, 1]
    fields = {}
    for e_i, p in enumerate(ex):
        _, cv_true = _lat_from_theta(theta_te[p], verts, sensor_idx, dx, src_rc)
        _, cv_rec = _lat_from_theta(mu[p], verts, sensor_idx, dx, src_rc)
        fields[f"CV_true_patient{e_i + 1}"] = cv_true
        fields[f"CV_recovered_patient{e_i + 1}"] = cv_rec
    field_units = {k: "mm/ms" for k in fields}

    trace = build_mesh_field_trace(
        case_id=CASE_ID, view_kit="CardiacMeshKit", vertices=verts, triangles=tris,
        fields=fields, field_units=field_units, sensors=None, isochrones_ms=[], coord_nd=2,
        summary={"substrate_loc_error_mm": metrics["substrate_loc_error_mm"],
                 "posterior_calibration_2sigma": metrics["posterior_calibration_2sigma"],
                 "speedup_factor": metrics["speedup_factor"]},
    )
    return BakeResult(
        case_id=CASE_ID, trace=trace, metrics=metrics,
        params={"n_grid": N_GRID, "n_sensors": N_SENSORS, "n_population": N_POP, "n_test": N_TEST},
        onnx=None, web_drivable=False, flags=[],
    )


SPEC = CaseSpec(
    id=CASE_ID,
    title="Amortized operator for instant personalization",
    category="electrophysiology-inverse",
    system_type="parameter-posterior",
    view_kit="CardiacMeshKit",
    real_or_synthetic="synthetic",
    expected_band="trained once on a simulated patient population, the operator maps a new patient's sparse "
                  "activation times in one forward pass to a calibrated posterior over the tissue parameters "
                  "(conduction velocity and substrate location), at a large speedup over a per-patient fit",
    engine_desc="amortized heteroscedastic operator over a simulated Eikonal population -> calibrated parameter posterior; recalibrated UQ",
    ladder={
        "classical": "per-patient inverse fit repeated from scratch for every patient (minutes each)",
        "sota": "geometry-independent neural operators for cardiac EP (DeepONet-ViT, kernel operator learning)",
        "novel": "amortized inference: one operator over a simulated population returns a CALIBRATED parameter posterior in one pass, no per-patient refit",
    },
    references=[
        {"cite": "A unified framework for geometry-independent operator learning in cardiac electrophysiology (2025)",
         "doi_or_arxiv": "arXiv:2512.01702", "note": "DeepONet-ViT / operator-learning SOTA for cardiac EP"},
        {"cite": "Kissas, Seidman, Perdikaris (2022). Learning operators with coupled attention. JMLR 23",
         "doi_or_arxiv": "arXiv:2201.01032", "note": "attention-based operator learning (amortized maps)"},
    ],
    build=_build,
    tags=["amortized-inference", "neural-operator", "personalization", "digital-twin", "parameter-posterior", "beyond-sota", "stretch"],
)
